FROM ubuntu:latest
# Commentaire
# INSTRUCTION arguments

RUN apt-get update \
    && apt-get install -y curl \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs